name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches-ignore:
      # dependabot changes are tested as branch pushes
      - 'dependabot/**'

jobs:
  build-prep:
    name: Resolve versions to build
    runs-on: ubuntu-latest
    outputs:
      kind-version: ${{ steps.kind.outputs.version }}
      kubernetes: ${{ steps.kubernetes.outputs.version }}
      kubernetes-1.37: ${{ steps.kubernetes.outputs['1.37'] }}
      kubernetes-1.36: ${{ steps.kubernetes.outputs['1.36'] }}
      kubernetes-1.35: ${{ steps.kubernetes.outputs['1.35'] }}
      kubernetes-1.34: ${{ steps.kubernetes.outputs['1.34'] }}
      kubernetes-1.33: ${{ steps.kubernetes.outputs['1.33'] }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: Resolve kind version
      id: kind
      run: echo "version=$(go list -modfile hack/kind/go.mod -m -f '{{.Version}}' sigs.k8s.io/kind)" | tee -a "${GITHUB_OUTPUT}"
      env:
        GOTOOLCHAIN: auto
    - name: Resolve kubernetes version
      id: kubernetes
      run: |
        set -euo pipefail

        echo "version=$(go list -modfile hack/kubernetes/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.37=$(go list -modfile hack/kubernetes-1.37/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.36=$(go list -modfile hack/kubernetes-1.36/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.35=$(go list -modfile hack/kubernetes-1.35/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.34=$(go list -modfile hack/kubernetes-1.34/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.33=$(go list -modfile hack/kubernetes-1.33/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
      env:
        GOTOOLCHAIN: auto

  build:
    name: Build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      packages: write
    needs: build-prep
    strategy:
      matrix:
        include:
        - kubernetes: ${{ needs.build-prep.outputs.kubernetes }}
          latest: true
        - kubernetes: ${{ needs.build-prep.outputs['kubernetes-1.37'] }}
        - kubernetes: ${{ needs.build-prep.outputs['kubernetes-1.36'] }}
        - kubernetes: ${{ needs.build-prep.outputs['kubernetes-1.35'] }}
        - kubernetes: ${{ needs.build-prep.outputs['kubernetes-1.34'] }}
        - kubernetes: ${{ needs.build-prep.outputs['kubernetes-1.33'] }}
    uses: ./.github/workflows/publish.yaml
    with:
      kind-version: ${{ needs.build-prep.outputs.kind-version }}
      kubernetes-version: ${{ matrix.kubernetes }}
      latest: ${{ matrix.latest || false }}
    secrets: inherit

  test:
    name: Test
    needs: build
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped')
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: defaults
        - name: k8s-v1.37
          kubernetes-version: v1.37
        - name: k8s-v1.36
          kubernetes-version: v1.36
        - name: k8s-v1.35
          kubernetes-version: v1.35
        - name: k8s-v1.34
          kubernetes-version: v1.34
        - name: k8s-v1.33
          kubernetes-version: v1.33
        - name: local-registry
          registry: {}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: OCI registry
      id: registry
      if: matrix.registry
      uses: reconcilerio/registry@v1
      with: ${{ matrix.registry || fromJson('{}') }}
    - name: kind cluster
      id: cluster
      uses: ./
      with:
        kubernetes-version: ${{ matrix.kubernetes-version }}
        registry: ${{ steps.registry.outputs.registry }}
        registry-ca: ${{ steps.registry.outputs.tls-ca }}
    - name: Cluster info
      run: |
        set -euo pipefail

        echo "cluster context: ${{ steps.cluster.outputs.context }}"
        echo "kubernetes version: ${{ steps.cluster.outputs.kubernetes-version }}"
    - name: Run a pod
      run: |
        set -euo pipefail

        image="busybox"
        registry="${{ steps.registry.outputs.registry }}"
        if [[ "${registry}" != "" ]] ; then
          echo "##[group]copy image into local registry"
            crane copy "${image}" "${registry}/test/${image}"
            image="${registry}/test/${image}"
          echo "##[endgroup]"
        fi

        echo "##[group]run image"
          kubectl run get-env --image="${image}" -it --restart=Never -- env
        echo "##[endgroup]"

    - name: Collect logs
      if: always()
      uses: ./logs

  done:
    # used as a non-matrix job for protected branches
    name: Done
    needs: test
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
    - run: echo "That's all folks"
