name: Node image

on:
  workflow_call:
    inputs:
      kind-version:
        description: kind version to use
        required: true
        type: string
      kind-base-artifact-name:
        description: artifact name holding the base image
        required: true
        type: string
      kind-base-digest:
        description: digest for the base image
        required: true
        type: string
      kubernetes-version:
        description: kubernetes version to use
        required: true
        type: string
      cloud-provider-kind-version:
        description: cloud-provider-kind version to use
        required: true
        type: string
        default: "auto"
      repository:
        description: nested image repository to publish into
        type: string
        default: ""
      tag:
        description: primary image tag to publish
        required: true
        type: string
      additional-tags:
        description: new line delimited set of additional tags to add to the published image
        type: string
      publish:
        description: publish built image
        type: boolean
        default: true
      force:
        description: force overwriting an existing image
        type: boolean
        default: false
      id:
        description: identifier to distinguish calls within a matrix
        type: string
    outputs:
      artifact-name:
        description: uploaded node image artifact name
        value: "kind-node-${{ inputs.tag }}-${{ inputs.id || '0'}}"
      digest:
        description: digest for node image
        value: "${{ case(inputs.force || ! jobs.preflight.outputs.existing-digest, jobs.assemble.outputs.digest, jobs.preflight.outputs.existing-digest)  }}"

concurrency:
  group: ${{ case(inputs.publish, inputs.tag, format('run-{0}-{1}', inputs.id || github.run_id, inputs.tag)) }}
  queue: max

env:
  artifact-name: "kind-node-${{ inputs.tag }}-${{ inputs.id || '0'}}"
  repository: "${{
    case(inputs.repository == '',
    format('ghcr.io/{0}/node', github.repository),
    format('ghcr.io/{0}/node/{1}', github.repository, inputs.repository)
    )
    }}"

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      existing-digest: ${{ steps.existing.outputs.digest }}
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: Check for existing image
        id: existing
        run: |
          set -euo pipefail

          digest="$(crane digest "${{ env.repository }}:${{ inputs.tag }}" || echo -n '')"
          echo "digest=${digest}" | tee -a "${GITHUB_OUTPUT}"

  build:
    name: Build ${{ matrix.os }}/${{ matrix.arch }}
    needs: preflight
    if: ${{ inputs.force || ! needs.preflight.outputs.existing-digest }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            runs-on: ubuntu-24.04
          - os: linux
            arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: Install kind
        uses: reconcilerio/install-kind-action@v1
        with:
          version: ${{ inputs.kind-version }}
      - name: OCI registry
        id: registry
        uses: reconcilerio/registry@v1
      - name: Download base image
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.kind-base-artifact-name }}"
          path: "${{ inputs.kind-base-artifact-name }}"
      - name: Push base image
        run: |
          crane push \
            "${{ inputs.kind-base-artifact-name }}" \
            "${{ steps.registry.outputs.registry }}/base@${{ inputs.kind-base-digest }}"
      - name: Checkout kubernetes ${{ inputs.kubernetes-version }}
        uses: actions/checkout@v7
        with:
          repository: kubernetes/kubernetes
          path: kubernetes
          ref: ${{ inputs.kubernetes-version }}
      - name: Build kind ${{ matrix.arch }} node image
        run: |
          set -euo pipefail

          kind build node-image ./kubernetes \
            --arch ${{ matrix.arch }} \
            --base-image "${{ steps.registry.outputs.registry }}/base@${{ inputs.kind-base-digest }}" \
            --image "${{ steps.registry.outputs.registry }}/node" \
            --type release

          docker push ${{ steps.registry.outputs.registry }}/node

          crane pull --format oci \
            "${{ steps.registry.outputs.registry }}/node" \
            "${{ env.artifact-name }}-${{ matrix.arch }}"
      - uses: actions/upload-artifact@v7
        with:
          name: "${{ env.artifact-name }}-${{ matrix.arch }}"
          path: "${{ env.artifact-name }}-${{ matrix.arch }}"
          retention-days: 7

  assemble:
    name: Assemble
    needs: build
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.assemble.outputs.digest }}
      digest-amd64: ${{ steps.assemble.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.assemble.outputs.digest-arm64 }}
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: OCI registry
        id: registry
        uses: reconcilerio/registry@v1
      - name: Download staged image amd64
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}-amd64"
          path: "${{ env.artifact-name }}-amd64"
      - name: Download staged image arm64
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}-arm64"
          path: "${{ env.artifact-name }}-arm64"
      - name: Assemble node image index
        id: assemble
        run: |
          set -euo pipefail

          crane push \
            "${{ env.artifact-name }}-amd64" \
            "${{ steps.registry.outputs.registry }}/node:amd64"
          crane push \
            "${{ env.artifact-name }}-arm64" \
            "${{ steps.registry.outputs.registry }}/node:arm64"

          crane index append \
            -m ${{ steps.registry.outputs.registry }}/node:amd64 \
            -m ${{ steps.registry.outputs.registry }}/node:arm64 \
            -t ${{ steps.registry.outputs.registry }}/node

          echo "digest=$(crane digest "${{ steps.registry.outputs.registry }}/node")" | tee -a "${GITHUB_OUTPUT}"
          echo "digest-amd64=$(crane digest "${{ steps.registry.outputs.registry }}/node:amd64")" | tee -a "${GITHUB_OUTPUT}"
          echo "digest-arm64=$(crane digest "${{ steps.registry.outputs.registry }}/node:arm64")" | tee -a "${GITHUB_OUTPUT}"

          crane pull --format oci \
            "${{ steps.registry.outputs.registry }}/node" \
            "${{ env.artifact-name }}"
      - uses: actions/upload-artifact@v7
        with:
          name: "${{ env.artifact-name }}"
          path: "${{ env.artifact-name }}"
          retention-days: 7

  test:
    name: Test (${{ matrix.os }}/${{ matrix.arch }})
    needs: assemble
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            runs-on: ubuntu-24.04
          - os: linux
            arch: arm64
            runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: OCI registry
        id: registry
        uses: reconcilerio/registry@v1
      - name: Download staged image
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}"
          path: "${{ env.artifact-name }}"
      - name: Push node image index
        run: |
          set -euo pipefail

          crane push \
            "${{ env.artifact-name }}" \
            "${{ steps.registry.outputs.registry }}/node@${{ needs.assemble.outputs.digest }}"
      - name: kind cluster
        id: cluster
        uses: ./
        with:
          kubernetes-version: ${{ steps.registry.outputs.registry }}/node@${{ needs.assemble.outputs.digest }}
          cloud-provider-kind-version: ${{ inputs.cloud-provider-kind-version }}
          registry: ${{ steps.registry.outputs.registry }}
          registry-ca: ${{ steps.registry.outputs.tls-ca }}
      - name: Run a pod
        run: |
          set -euo pipefail

          image="traefik/whoami"
          registry="${{ steps.registry.outputs.registry }}"
          if [[ "${registry}" != "" ]] ; then
            echo "##[group]copy image into local registry"
              crane copy "${image}" "${registry}/test/${image}"
              image="${registry}/test/${image}"
            echo "##[endgroup]"
          fi

          echo "##[group]run image"
            cat <<EOF | kubectl apply -f -
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test
            labels:
              app: test
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: test
            template:
              metadata:
                labels:
                  app: test
              spec:
                containers:
                - name: test
                  image: ${image}
                  ports:
                  - containerPort: 80

          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: test
          spec:
            type: LoadBalancer
            selector:
              app: test
            ports:
            - port: 80

          EOF

            kubectl wait deployments.apps/test --for condition=available --timeout 1m
            kubectl wait service/test --for=jsonpath='{.status.loadBalancer.ingress}' --timeout 1m
            ingress_ip=$(kubectl get svc test -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')

            value=$(curl -s http://${ingress_ip}/bench)
            if [ "${value}" == "1" ]; then
              echo "/bench: ${value}"
            else
              echo "Unexpected /bench: got ${value}, wanted 1"
              exit 1
            fi
          echo "##[endgroup]"
      - name: Collect logs
        if: always()
        uses: ./logs
        with:
          artifact-name: "kind-logs-${{ inputs.kubernetes-version }}-${{ matrix.os }}-${{ matrix.arch }}"

  publish:
    name: Publish
    needs:
      - test
      - assemble
    if: inputs.publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.2
      - name: Download staged image
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}"
          path: "${{ env.artifact-name }}"
      - name: Download staged image amd64
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}-amd64"
          path: "${{ env.artifact-name }}-amd64"
      - name: Download staged image arm64
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.artifact-name }}-arm64"
          path: "${{ env.artifact-name }}-arm64"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          set -euo pipefail

          crane push \
            "${{ env.artifact-name }}" \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest }}"
          crane push \
            "${{ env.artifact-name }}-amd64" \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-amd64 }}"
          crane push \
            "${{ env.artifact-name }}-arm64" \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-arm64 }}"
      - name: Sign
        run: |
          set -euo pipefail

          cosign sign --yes \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest }}"
          cosign sign --yes \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-amd64 }}"
          cosign sign --yes \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-arm64 }}"
      - name: Primary tag
        run: |
          set -euo pipefail

          crane tag \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-amd64 }}" \
            "${{ inputs.tag }}-amd64"
          crane tag \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest-arm64 }}" \
            "${{ inputs.tag }}-arm64"
          crane tag \
            "${{ env.repository }}@${{ needs.assemble.outputs.digest }}" \
            "${{ inputs.tag }}"

  tag:
    name: Tag
    needs: publish
    if: always() && !failure() && !cancelled() && inputs.publish && inputs.additional-tags
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Install crane
        uses: reconcilerio/install-crane-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Additional tags
        run: |
          set -euo pipefail

          additional_tags="$(echo "${{ inputs.additional-tags }}" | awk '{$1=$1};1' | grep -v -e "^$")"

          while IFS= read -r tag; do
            crane tag \
              "${{ env.repository }}:${{ inputs.tag }}" \
              "${tag}"
          done <<< "${additional_tags}"
